# Welcome to Jekyll!
#

# Site settings
title: Pavitthra
description: |
  I'm an avid computer scientist and a  
  student. I like to shoot for the stars.
owner: Pavitthra Pandurangan # or company name #old color: #2e3842
first_published: 2017 # if migrating another site, the year of your first publish
email: pavitthp@andrew.cmu.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/pavitthrap
  linkedin-square: https://www.linkedin.com/in/pavitthra-pandurangan-620293102/
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: pavitthp@andrew.cmu.edu
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
